/*
 * bot-one
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: bot-one: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AnalyticsGenericEvent
    /// </summary>
    [DataContract(Name = "analyticsGenericEvent")]
    public partial class AnalyticsGenericEvent : IEquatable<AnalyticsGenericEvent>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsGenericEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnalyticsGenericEvent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsGenericEvent" /> class.
        /// </summary>
        /// <param name="createdAt">Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time.</param>
        /// <param name="varEvent">Event to be added (required).</param>
        /// <param name="id">Order in which events will be ingested (required).</param>
        /// <param name="properties">Key value pairs of the properties.</param>
        /// <param name="timeOffset">Time offset in seconds with server time.</param>
        public AnalyticsGenericEvent(long createdAt = default(long), string varEvent = default(string), long id = default(long), Dictionary<string, string> properties = default(Dictionary<string, string>), long timeOffset = default(long))
        {
            // to ensure "varEvent" is required (not null)
            if (varEvent == null)
            {
                throw new ArgumentNullException("varEvent is a required property for AnalyticsGenericEvent and cannot be null");
            }
            this.VarEvent = varEvent;
            this.Id = id;
            this.CreatedAt = createdAt;
            this.Properties = properties;
            this.TimeOffset = timeOffset;
        }

        /// <summary>
        /// Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time
        /// </summary>
        /// <value>Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time</value>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Event to be added
        /// </summary>
        /// <value>Event to be added</value>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public string VarEvent { get; set; }

        /// <summary>
        /// Order in which events will be ingested
        /// </summary>
        /// <value>Order in which events will be ingested</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public long Id { get; set; }

        /// <summary>
        /// Key value pairs of the properties
        /// </summary>
        /// <value>Key value pairs of the properties</value>
        [DataMember(Name = "properties", EmitDefaultValue = false)]
        public Dictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Time offset in seconds with server time
        /// </summary>
        /// <value>Time offset in seconds with server time</value>
        [DataMember(Name = "time_offset", EmitDefaultValue = false)]
        public long TimeOffset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsGenericEvent {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  VarEvent: ").Append(VarEvent).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  TimeOffset: ").Append(TimeOffset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AnalyticsGenericEvent);
        }

        /// <summary>
        /// Returns true if AnalyticsGenericEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of AnalyticsGenericEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnalyticsGenericEvent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CreatedAt == input.CreatedAt ||
                    this.CreatedAt.Equals(input.CreatedAt)
                ) && 
                (
                    this.VarEvent == input.VarEvent ||
                    (this.VarEvent != null &&
                    this.VarEvent.Equals(input.VarEvent))
                ) && 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Properties == input.Properties ||
                    this.Properties != null &&
                    input.Properties != null &&
                    this.Properties.SequenceEqual(input.Properties)
                ) && 
                (
                    this.TimeOffset == input.TimeOffset ||
                    this.TimeOffset.Equals(input.TimeOffset)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                if (this.VarEvent != null)
                {
                    hashCode = (hashCode * 59) + this.VarEvent.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Properties != null)
                {
                    hashCode = (hashCode * 59) + this.Properties.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TimeOffset.GetHashCode();
                return hashCode;
            }
        }

    }

}
