/*
 * bot-one
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: bot-one: v2 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AnalyticsServerTime
    /// </summary>
    [DataContract(Name = "analyticsServerTime")]
    public partial class AnalyticsServerTime : IEquatable<AnalyticsServerTime>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsServerTime" /> class.
        /// </summary>
        /// <param name="serverTime">serverTime.</param>
        public AnalyticsServerTime(string serverTime = default(string))
        {
            this.ServerTime = serverTime;
        }

        /// <summary>
        /// Gets or Sets ServerTime
        /// </summary>
        [DataMember(Name = "server_time", EmitDefaultValue = false)]
        public string ServerTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsServerTime {\n");
            sb.Append("  ServerTime: ").Append(ServerTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AnalyticsServerTime);
        }

        /// <summary>
        /// Returns true if AnalyticsServerTime instances are equal
        /// </summary>
        /// <param name="input">Instance of AnalyticsServerTime to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnalyticsServerTime input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ServerTime == input.ServerTime ||
                    (this.ServerTime != null &&
                    this.ServerTime.Equals(input.ServerTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServerTime != null)
                {
                    hashCode = (hashCode * 59) + this.ServerTime.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
