/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v3 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AnalyticsBatchCreateAppEventRequest
    /// </summary>
    [DataContract(Name = "analyticsBatchCreateAppEventRequest")]
    public partial class AnalyticsBatchCreateAppEventRequest : IEquatable<AnalyticsBatchCreateAppEventRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsBatchCreateAppEventRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnalyticsBatchCreateAppEventRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsBatchCreateAppEventRequest" /> class.
        /// </summary>
        /// <param name="data">Events array (required).</param>
        public AnalyticsBatchCreateAppEventRequest(List<AnalyticsGenericEvent> data = default(List<AnalyticsGenericEvent>))
        {
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for AnalyticsBatchCreateAppEventRequest and cannot be null");
            }
            this.Data = data;
        }

        /// <summary>
        /// Events array
        /// </summary>
        /// <value>Events array</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public List<AnalyticsGenericEvent> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsBatchCreateAppEventRequest {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AnalyticsBatchCreateAppEventRequest);
        }

        /// <summary>
        /// Returns true if AnalyticsBatchCreateAppEventRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AnalyticsBatchCreateAppEventRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnalyticsBatchCreateAppEventRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Data == input.Data ||
                    this.Data != null &&
                    input.Data != null &&
                    this.Data.SequenceEqual(input.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Data != null)
                {
                    hashCode = (hashCode * 59) + this.Data.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
