/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v3 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// CreateUserEventRequest
    /// </summary>
    [DataContract(Name = "CreateUserEvent_request")]
    public partial class CreateUserEventRequest : IEquatable<CreateUserEventRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateUserEventRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateUserEventRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateUserEventRequest" /> class.
        /// </summary>
        /// <param name="createdAt">Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time.</param>
        /// <param name="properties">Key value pairs of the properties.</param>
        /// <param name="timeOffset">Time offset in seconds with server time.</param>
        /// <param name="userId">UserID of the affected user (required).</param>
        public CreateUserEventRequest(long createdAt = default(long), Dictionary<string, string> properties = default(Dictionary<string, string>), long timeOffset = default(long), string userId = default(string))
        {
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for CreateUserEventRequest and cannot be null");
            }
            this.UserId = userId;
            this.CreatedAt = createdAt;
            this.Properties = properties;
            this.TimeOffset = timeOffset;
        }

        /// <summary>
        /// Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time
        /// </summary>
        /// <value>Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time</value>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Key value pairs of the properties
        /// </summary>
        /// <value>Key value pairs of the properties</value>
        [DataMember(Name = "properties", EmitDefaultValue = false)]
        public Dictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Time offset in seconds with server time
        /// </summary>
        /// <value>Time offset in seconds with server time</value>
        [DataMember(Name = "time_offset", EmitDefaultValue = false)]
        public long TimeOffset { get; set; }

        /// <summary>
        /// UserID of the affected user
        /// </summary>
        /// <value>UserID of the affected user</value>
        [DataMember(Name = "user_id", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateUserEventRequest {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  TimeOffset: ").Append(TimeOffset).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateUserEventRequest);
        }

        /// <summary>
        /// Returns true if CreateUserEventRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateUserEventRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateUserEventRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CreatedAt == input.CreatedAt ||
                    this.CreatedAt.Equals(input.CreatedAt)
                ) && 
                (
                    this.Properties == input.Properties ||
                    this.Properties != null &&
                    input.Properties != null &&
                    this.Properties.SequenceEqual(input.Properties)
                ) && 
                (
                    this.TimeOffset == input.TimeOffset ||
                    this.TimeOffset.Equals(input.TimeOffset)
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                if (this.Properties != null)
                {
                    hashCode = (hashCode * 59) + this.Properties.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TimeOffset.GetHashCode();
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
